rostopic: /imu
update_rate: 200.0 #Hz

accelerometer_noise_density: 2.64e-02 #continous
accelerometer_random_walk: 7.21e-04 
gyroscope_noise_density: 3.18e-03 #continous
gyroscope_random_walk: 3.07e-05



